### PR TITLE
Welcoming contact field

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by DerGoogler** [comment]
Useless. You should follow the Community Guidelines.

**Comment by DerGoogler** [comment]
`CODE_OF_CONDUCT.md` shouldn't be deleted and `CONTACT.md` is an useless file just to view only ONE link.

The Telegram community link can also in `README.md`.

**Review by DerGoogler — CHANGES_REQUESTED** [review]
Please restore.

**Comment by Fox2Code** [comment]
Hi, code of conduct is something to ask user to show respect.
You are welcome to suggest changes on telegram or by creating an issue/pr on GitHub
I may try to do additional change to make the code of conduct more welcoming in the future.

Also please note that disagreeing with the code of conduct isn't against the code of conduct.

**Comment by comradekingu** [comment]
Very happy that you aren't following the CoC, which is laudable.
That being the case, we only have to objectively read what it says instead of substituting it for further laudable intent.
it still has a function and an intent that isn't compatible with libre software.
That is my reason for contributing, so I care more about things that take away from it.
Unsurprisingly its creator has gone on to make a non-libre license, and attacked libre software at large.

@DerGoogler To facilitate deescalation of conflict subject to the faculties of actually involved parties is not useless,
yet another function is that of escalating conflict to also include maintainer(s).

I didn't actually accept the CoC. To the contrary I expressly disagreed with it for my contributions.
As that makes me a contributor, I have thus not "pledged" to follow it, like it unequivocally says.
In turn, selling others on the idea that this has in fact taken place hinges on the same premise as actually asking ones contributors to have it implemented beforehand. There is a fundamental disconnect on both entry and takeaway.
What does happen is false security is instilled in vulnerable individuals.
People anti-social enough to carry out behavior that would be mentioned in unwritten rules are OTOH not affected, and not thwarted because it means also disobeying a text-file.
I found the time to explain myself now, but logically there is no explanation given in any project for implementing one.
It is always "get green lights", or "important", and so on. So at scale, there is no knowing why it is ever used, making it at best meaningless.

@Fox2Code 
What it says is "rules that applies to everyone interacting with the repo".
That is a variant section, which is also undermined in a variant section.
At best ambigous, for a text-file that doesn't get read to begin with, and you can try to recite it to
find out how much of it is remembered.

>Community leaders have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct

Complete retroactive removal of all traces.
It is an inspired reading to skirt "responsibility" to mean it is optional. All for it though.
Do note that in earlier versions it used to say "project maintainers" where it now says "community leaders".
This is because it is purposefully anti-meritocratic.

I appreciate changing things to "may follow" aligns with better intent than what is to be found originally,
but nontheless it is under the banner of what is otherwise and normally an authoritarian text-file that puts itself before all else.

For how supposedly optional its implementation or content is, it says "Examples of unacceptable behavior include:"
"Unacceptable" is not vague at all.

For example
>  conduct which could reasonably be considered inappropriate in a professional setting

is listed. This values corporate values over community.

What is vague is the implementation of justice by people without vested interest in the project.
Their actions are required to be handled in secret, and can occur fully behind closed doors.
This power is not limited, and it is all-encompassing

>within all community spaces, and also applies when
an individual is officially representing the community in public spaces.

It encroaches on human nature
>  sexual advances of any kind

The idea here is "harassment" is redefined.
In this meaning it is a good-sounding premise that in practice is not achievable without undoing sexuality.
Like the catholic church implementing a CoC first, it hasn't worked since.

If I wanted to instrument the most authoritarian system of governance I would make it this, and sell it with rosy words.
Notice also that immutable characteristics are invoked for no good reason.
This creates division.
Why should people have to be singled out in files they are expected to read, for every project one contributes to?
We can easily discern that a statedly political document that bans politics isn't all about "respect".

If no fault can be found, one will be produced.

>This includes avoiding interactions in community spaces as well as external channels
like social media. Violating these terms may lead to a temporary or permanent ban.

This is a text-file that produces disasters, has otherwise only wasted time, and gains ever more bloat in every reason, as it becomes more and more apparent what its underlying mechanics are. For that reason it is also increasingly unpopular.
It is a magnet to anti-social people, and it gives them all the best possible tools imaginable. Unvetted ultimate power.
Removing is to the contrary never a problem, and I am happy to report a text that can be recited from memory (and making zero assumptions) works a lot better.

I don't like having to outlaw instilling hatred, because it does paint a rather crude image of contributors.
>Respecting mistakes as something happening to everyone that is useful as learning material

This I like.

**Comment by Fox2Code** [comment]
@comradekingu thank for the suggestions to the code of conduct, it was initially added by @androidacybot because it was used by a lot of project, while I agree having rules is important, I also agree that the language used in it is very hostile.

I will be working on a rework of the code of conduct to be more user friendly.

**Comment by comradekingu** [comment]
The reason it can be clicked into being is because it was made by a GitHub employee in charge of inclusion, that later got fired for not welcoming new members of the team.
That is also the reason most people having one haven't read it themselves.
The terms of service isn't optional, and the ruleset that GitHub actually also has is redundant to a set of rules.
People generally don't know that GitHub has a set of rules.

As per EU-GDPR, visiting a site is not compliance. I explicitly disagreed.
I don't disagree as to what rules are, and what they do. A CoC isn't that. A CoC is a way to instrument power, and here lays out a means of achieving power that rivals how libre software projects operate and come into being.
I only mentioned harassment in the sense of the CoC, which isn't the same as the legally defined concept.
Bending and falsifying language to fit a political agenda isn't new.
This CoC hasn't helped any community, but is rather used for political reason to exert power.

It is possible to have it, but it is incompatible if you want to put it in the license.
I do find LGBTQ issues out of place, which is why I find the "## Our Pledge" part to be out of place.

@Fox2Code More projects don't have one, and that worked just as well as even the projects that now have one for largely no reason.
CoCs have never been user friendly. People leave projects on sight because of them, because it signals that the governance might be politically motivated, by a further politically motivated document.
If you start at my attempt (which isn't a CoC), that instruments privacy, and leads the way to amicable solutions.
Pages worth of bloat isn't a great way to find:

>Respecting mistakes as something happening to everyone is useful learning material

it makes sense, because it is something one can work out that the maintainer writing it actually believes in.

**Comment by Fox2Code** [comment]
You don't have to agree to CoC to be banned to the repo, the CoC is supposed to be like rules, not a contrat.

It's role isn't to have any legal value.

I will rewrite it later a give the code of conduct a new name.

**Pull request closed without merging**
