### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Comment by xerta555** [comment]
Need to be translated



Need to be improved

**Comment by xerta555** [comment]
> @xerta555 looks like you need some more work. Build fails with your updates

Need to be translatable
image

**Comment by Fox2Code** [comment]
`@android:string/something` is a reference to a system resource, replace it directly by `Something` instead.

**Comment by xerta555** [comment]
> `@android:string/something` is a reference to a system resource, replace it directly by `Something` instead.

But it must be translated...

**Comment by xerta555** [comment]
> > > @xerta555 looks like you need some more work. Build fails with your updates
> > 
> > 
> > Need to be translatable image
> 
> You're trying to reference another (nonexistent) string within a string which won't work. Directly put the translation instead of any `@android` notation

Ok but how to translate "yes" "no" and "cancel" so ?

**Comment by xerta555** [comment]
> Just put the string where you have the @android stuff now and maybe remove translateable=false

I hesitate to do that but i don't want to break more things

**Comment by Fox2Code** [comment]
This is valid:
```
    <string name="yes" translatable="false">Oui</string>
    <string name="no" translatable="false">Non</string>
    <string name="cancel" translatable="false">Annuler</string>
```

**Comment by Fox2Code** [comment]
Thank you! :3

**Pull request merged**
