### PR TITLE
Add Simplified Chinese

### PR DESCRIPTION
**Pull request by ender-zhao**
arrays.xml

### CODE REVIEW

**Comment by Fox2Code** [comment]
Thanks, this is perfect. Merging this and #17

**Comment by Fox2Code** [comment]
Oops didn't see you named it `strings.xml` instead of `array.xml`, don't worry about that, I can manage to fix this on my side, or you can fix the file name for merge.

**Comment by ender-zhao** [comment]
I have fix.

**Comment by Fox2Code** [comment]
Thanks!

**Pull request merged**
