### PR TITLE
Translated using Weblate (Polish)

### PR DESCRIPTION
**Pull request by Daviteusz**
Currently translated at 100.0% (148 of 148 strings)

### CODE REVIEW

**Comment by Leshu7w7** [comment]
Hi, would you mind telling me how I can set up weblate for future translations?

**Comment by Daviteusz** [comment]
> Hi, would you mind telling me how I can set up weblate for future translations?

I selfhosted weblate on raspberrypi:

- https://docs.weblate.org/en/latest/admin/install/docker.html

Here you can find how to set up project

- https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components

And everything about version controlling:

- https://docs.weblate.org/en/latest/vcs.html

**Comment by Fox2Code** [comment]
@Daviteusz thx, I have a VPS I can use for weblate, so it might be worth checking.

**Comment by Fox2Code** [comment]
Link to weblate issue so I don't forget it: #117

**Pull request merged**
