### PR TITLE
Add expandable card

### PR DESCRIPTION
**Pull request by DerGoogler**
image

### CODE REVIEW

**Comment by DerGoogler** [comment]
> I'm a little confused as to what this does, your screenshot doesn't seem to show anything different than now

Please check https://t.me/Fox2Code_Chat/11849

**Comment by Fox2Code** [comment]
I'm conflicted about the PR, I think I'll probably merge this at some point for the next major UI rework release.

**Comment by Fox2Code** [comment]
There is still room to make UI compact in other ways, I think I will use the empty space for something else.

**Comment by HiFiiDev** [comment]
👀

**Pull request closed without merging**
