### PR TITLE
nb_NO translation

### PR DESCRIPTION
**Pull request by comradekingu**
Can be merged before next version.
Don't agree to the CoC.

### CODE REVIEW

**Comment by Fox2Code** [comment]
What is "nb-rNO", I need to know the language your are adding before accepting the pull request.
This is so I can add you to next change-log.

**Comment by Fox2Code** [comment]
@comradekingu are you here?

**Comment by comradekingu** [comment]
@Fox2Code Yes
nb_NO is "Norwegian Bokmål"

**Comment by Fox2Code** [comment]
Code of conduct was made by @androidacybot
Not being in change-log doesn't mean it doesn't apply to you.
Just know I do not enforce rules strictly to avoid any discomfort.
If you change you mind before next release you can join https://t.me/Fox2Code_Chat or comment in this PR so I can change the change-log to add you back.
I have a text file on my desktop with FoxMMM change-log.

**Comment by Fox2Code** [comment]
Also not agreeing of code of conduct doesn't means it doesn't apply here.
As such I consider this as optional as any severe violation can still result in repo ban.
If you think the code of conduct should be changed I still accept PRs about it to improve it.

**Pull request merged**
